# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03fce8134eda68c83cf4c6e681d59d16350247fa9019c1b717f2ab53c8dc4d32f6804ad2c0d0e502aa616aabe973560655cb5331a93b6c487582928977231897

test:
  secret_key_base: 552553bdc7872aa4b8fc5948f1daab36a0e5dfbb3b9bf3ca9261237413361226a2b5900e0ec8d613c02ca33f0c22aa75452a825bc957d448368918c2178a1adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
